name: Placas
main: placas.core.Placas
version: 1.0
commands:
  editar:
    description: Edita uma placa
    usage: ยง9Use- ยง7/editar ยงb<linha 1-4> <texto>  ยง7(Enquanto olha para uma placa);
    permission: fallcraft.placas.editar